### ISSUE TITLE
Crear sitio web del WPD 2014

### ISSUE THREAD

**Issue by macagua** [plone-ve/plone-ve.github.com#1]
Hola @arawako 
- Se necesita con URGENCIA.
- Debe usar inicialmente la misma estructura del ve plone day 2013 > http://plone-ve.github.io/veploneday/2013/ claro esta actualizada con la información acá definida https://plone.org/events/wpd/hosts/caracas-venezuela (esta privada aun PRIVADA necesita iniciar sesión, ya tienes permisos)
- La dirección url debe ser http://plone-ve.github.io/wpd/2014/ esto responde a la estructura de carpeta de este repositorio, y la razón de usarla así es que esta url es la usada para las invitaciones y soporte.

**Comment by macagua** [comment]
@arawako alguna duda me avisa!

**Comment by jlv-code** [comment]
@macagua @arawako ya están en ello? porque puedo echarles una mano...

**Comment by macagua** [comment]
@jlv-code no hay nada hasta ahora puedes empezar y coordinar con @arawako 

La idea es basarse en la misma plantilla anterior del ve plone day 2013 y publicarlo con la estructura de directorio propuesta.

Si necesitas acceso a la ficha del WPD de Caracas en plone.org, create un usuario en el sitio de Plone y me lo pasas para compartir contigo el contenido que aun esta privado ;)

Gracias por tu interes y apoyo!

**Comment by jlv-code** [comment]
@macagua mi usuario es: jlvieitez

**Comment by macagua** [comment]
@jlv-code ok te compartí el documento

**Comment by macagua** [comment]
@jlv-code y @arawako algun avance sobre esta tarea?

**Comment by jlv-code** [comment]
@macagua @arawako Estoy en el diseño hermanos!

**Comment by macagua** [comment]
@jlv-code @arawako gracias por su colaboración en el sitio http://plone-ve.github.io/wpd/2014/
